name: 'Clinical Audit Pack'
description: |
  Run standard clinical audit checks (lint, typecheck, tests) and upload artifacts.

inputs:
  python_version:
    required: false
    default: '3.11'
    description: 'Python version to use'
  install-command:
    required: false
    default: ''
    description: 'Optional install command. Leave empty if dependencies are preinstalled.'
  lint-command:
    required: false
    default: 'ruff check src tests && ruff format --check src tests'
    description: 'Lint/format command'
  typecheck-command:
    required: false
    default: 'mypy src'
    description: 'Typecheck command'
  test-command:
    required: false
    default: 'pytest -q'
    description: 'Test command'
  run-lint:
    required: false
    default: 'true'
    description: 'Whether to run lint'
  run-typecheck:
    required: false
    default: 'true'
    description: 'Whether to run typecheck'
  run-tests:
    required: false
    default: 'true'
    description: 'Whether to run tests'
  artifacts-dir:
    required: false
    default: '.artifacts/audit'
    description: 'Directory for logs/results'
  artifact-name:
    required: false
    default: 'audit-artifacts'
    description: 'Artifact name to upload'
  enable_clinical:
    required: false
    default: 'false'
    description: 'Enable clinical OPA tests (opt-in)'
  opa_version:
    required: false
    default: 'v1.5.1'
    description: 'OPA version used for clinical tests'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - id: run-audit
      shell: bash
      env:
        INSTALL_COMMAND: ${{ inputs.install-command }}
        LINT_COMMAND: ${{ inputs.lint-command }}
        TYPECHECK_COMMAND: ${{ inputs.typecheck-command }}
        TEST_COMMAND: ${{ inputs.test-command }}
        RUN_LINT: ${{ inputs.run-lint }}
        RUN_TYPECHECK: ${{ inputs.run-typecheck }}
        RUN_TESTS: ${{ inputs.run-tests }}
        ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}
      run: |
        set +e
        mkdir -p "${ARTIFACTS_DIR}"
        overall_failed=0

        run_cmd() {
          name="$1"
          cmd="$2"

          if [ -z "${cmd}" ]; then
            echo "${name}: skipped (empty command)" | tee "${ARTIFACTS_DIR}/${name}.log"
            echo "0" > "${ARTIFACTS_DIR}/${name}.exit"
            return 0
          fi

          echo "[${name}] ${cmd}" | tee "${ARTIFACTS_DIR}/${name}.log"
          bash -lc "${cmd}" 2>&1 | tee -a "${ARTIFACTS_DIR}/${name}.log"
          code=${PIPESTATUS[0]}
          echo "${code}" > "${ARTIFACTS_DIR}/${name}.exit"

          if [ "${code}" -ne 0 ]; then
            overall_failed=1
          fi
        }

        if [ -n "${INSTALL_COMMAND}" ]; then
          run_cmd "install" "${INSTALL_COMMAND}"
        fi

        if [ "${RUN_LINT}" = "true" ]; then
          run_cmd "lint" "${LINT_COMMAND}"
        fi

        if [ "${RUN_TYPECHECK}" = "true" ]; then
          run_cmd "typecheck" "${TYPECHECK_COMMAND}"
        fi

        if [ "${RUN_TESTS}" = "true" ]; then
          run_cmd "tests" "${TEST_COMMAND}"
        fi

        {
          echo "Clinical Audit Pack"
          echo "run_lint=${RUN_LINT}"
          echo "run_typecheck=${RUN_TYPECHECK}"
          echo "run_tests=${RUN_TESTS}"
          echo "overall_failed=${overall_failed}"
        } > "${ARTIFACTS_DIR}/summary.txt"

        echo "overall_failed=${overall_failed}" >> "${GITHUB_OUTPUT}"

    - name: Clinical OPA tests (opt-in)
      if: ${{ inputs.enable_clinical == 'true' && hashFiles('policies/clinical/**') != '' }}
      shell: bash
      run: |
        set -euo pipefail
        curl -L -o opa "https://openpolicyagent.org/downloads/${{ inputs.opa_version }}/opa_linux_amd64_static"
        chmod +x opa
        sudo mv opa /usr/local/bin/opa
        opa test policies/clinical -v

    - name: Upload audit artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifacts-dir }}
        if-no-files-found: error
        retention-days: 30

    - name: Fail if any audit check failed
      if: ${{ steps.run-audit.outputs.overall_failed == '1' }}
      shell: bash
      run: |
        echo "audit-pack detected failing checks. Review artifacts."
        exit 1
