name: 'Compose Healthcheck'
description: 'Levanta stack docker compose, espera health_url, logs en fallo, down -v siempre.'
inputs:
  compose_file:
    required: false
    default: 'docker-compose.yml'
    description: 'Archivo docker-compose a usar'
  health_url:
    required: false
    default: 'http://localhost:8080/health'
    description: 'Endpoint de healthcheck'
  timeout_seconds:
    required: false
    default: '60'
    description: 'Timeout para healthcheck (segundos)'
  compose_args:
    required: false
    default: ''
    description: 'Argumentos extra para docker compose'
runs:
  using: 'composite'
  steps:
    - name: Levantar stack docker compose
      run: |
        docker compose -f ${{ inputs.compose_file }} up -d --build ${{ inputs.compose_args }}
    - name: Esperar healthcheck
      run: |
        for i in $(seq 1 $(( ${{ inputs.timeout_seconds }} / 3 ))); do
          if curl -fsSL ${{ inputs.health_url }}; then
            echo "Servicio saludable"; exit 0;
          fi
          sleep 3
        done
        echo "Timeout esperando healthcheck"; exit 1
    - name: Logs de servicios si falla
      if: failure()
      run: |
        docker compose -f ${{ inputs.compose_file }} logs
    - name: Bajar stack siempre
      if: always()
      run: |
        docker compose -f ${{ inputs.compose_file }} down -v
    required: false
    default: "docker-compose.yml"
  project-directory:
    description: "Directorio donde ejecutar docker compose."
    required: false
    default: "."
  profile:
    description: "Profile opcional de docker compose."
    required: false
    default: ""
  up-flags:
    description: "Flags para compose up."
    required: false
    default: "--build -d"
  down-flags:
    description: "Flags para compose down."
    required: false
    default: "down -v"
  health-url:
    description: "Endpoint de salud a validar."
    required: false
    default: "http://127.0.0.1:8000/health"
  timeout-seconds:
    description: "Tiempo maximo de espera para healthcheck."
    required: false
    default: "120"
  interval-seconds:
    description: "Intervalo entre reintentos de healthcheck."
    required: false
    default: "2"
  artifacts-dir:
    description: "Directorio para logs del compose."
    required: false
    default: ".artifacts/compose-healthcheck"
  artifact-name:
    description: "Nombre del artefacto de logs en GitHub Actions."
    required: false
    default: "compose-healthcheck-logs"

runs:
  using: "composite"
  steps:
    - id: run-compose-healthcheck
      shell: bash
      env:
        COMPOSE_FILE: ${{ inputs.compose-file }}
        PROJECT_DIR: ${{ inputs.project-directory }}
        PROFILE: ${{ inputs.profile }}
        UP_FLAGS: ${{ inputs.up-flags }}
        DOWN_FLAGS: ${{ inputs.down-flags }}
        HEALTH_URL: ${{ inputs.health-url }}
        TIMEOUT_SECONDS: ${{ inputs.timeout-seconds }}
        INTERVAL_SECONDS: ${{ inputs.interval-seconds }}
        ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}
      run: |
        set +e
        mkdir -p "${ARTIFACTS_DIR}"

        compose_cmd=(docker compose -f "${COMPOSE_FILE}")
        if [ -n "${PROFILE}" ]; then
          compose_cmd+=(--profile "${PROFILE}")
        fi

        read -r -a up_args <<< "${UP_FLAGS}"
        read -r -a down_args <<< "${DOWN_FLAGS}"

        failed=0

        pushd "${PROJECT_DIR}" >/dev/null || failed=1

        if [ "${failed}" -eq 0 ]; then
          "${compose_cmd[@]}" up "${up_args[@]}"
          if [ "$?" -ne 0 ]; then
            failed=1
          fi
        fi

        if [ "${failed}" -eq 0 ]; then
          elapsed=0
          timeout="${TIMEOUT_SECONDS}"
          interval="${INTERVAL_SECONDS}"

          while [ "${elapsed}" -lt "${timeout}" ]; do
            if curl -fsS "${HEALTH_URL}" >/dev/null; then
              break
            fi
            sleep "${interval}"
            elapsed=$((elapsed + interval))
          done

          if [ "${elapsed}" -ge "${timeout}" ]; then
            echo "Healthcheck timeout: ${HEALTH_URL}" | tee "${ARTIFACTS_DIR}/healthcheck.log"
            failed=1
          fi
        fi

        if [ "${failed}" -ne 0 ]; then
          "${compose_cmd[@]}" logs --no-color > "${ARTIFACTS_DIR}/compose.log" 2>&1 || true
        fi

        "${compose_cmd[@]}" "${down_args[@]}" >> "${ARTIFACTS_DIR}/teardown.log" 2>&1 || true

        popd >/dev/null || true

        echo "failed=${failed}" >> "${GITHUB_OUTPUT}"

    - name: Upload compose logs
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifacts-dir }}
        if-no-files-found: warn
        retention-days: 14

    - name: Fail if compose healthcheck failed
      if: ${{ steps.run-compose-healthcheck.outputs.failed == '1' }}
      shell: bash
      run: |
        echo "compose-healthcheck fallo."
        exit 1